name = "BigHogModsV2"
author = "hogger97"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18b6796ddded3110c62253af051f503072f53bd20f62e9cda6f01eed79600bb5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
