name = "BigHogModsV2"
author = "hogger97"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bfe9e5a64a1b0bf1997cd869ee1e1e716c5d95577d6df3ee480bb4077f028a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
