name = "BigHogModsV2"
author = "hogger97"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cae9df27cbc3e1ca1507c4792b2f6a5f3136e535f7dbcf5d50c06556d4ceb46f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
