name = "BigHogModsV2"
author = "hogger97"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22df7e745c13b2672ae5054a7f0fd5eeef7cf5b1dab077fd4198f30dd2a8711a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
